---

- name: rsyslog package {{ systemd_journal_rsyslog_package_state }}
  yum:
    name: rsyslog
    state: "{{ systemd_journal_rsyslog_package_state }}"

- name: create directory for persistent journal storage
  file:
    state: directory
    mode: 02755
    owner: root
    group: systemd-journal
    path: /var/log/journal
  when: systemd_journal_create_directory
  notify:
   - restart journald

- name: set configuration parameters in journald config
  ini_file:
    path: "{{ systemd_journal_configuration_file }}"
    owner: root
    group: root
    mode: 0644
    no_extra_spaces: yes
    section: Journal
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ lookup('dict', systemd_journal_configuration) }}"
  notify:
   - restart journald
